### ISSUE TITLE
Not working in Chrome 40.0.2214.91 m

### ISSUE THREAD

**Issue by roperi** [s3rvac/pygal-toggle-graphs#1]
Hi!

The toggle idea is fantastic! Many thanks! I haven't encountered a problem with Firefox nor Opera. So far only Chrome has let me down. 

Chrome 40.0.2214.91 m 
Windows 7 64 bit

Thanks!

**Comment by s3rvac** [comment]
Thank you for reporting the error. The problem was that GitHub started using `X-Content-Type-Options: nosniff` and Chrome 40 enforces strict MIME type checking. Therefore, I had to change the link to the script so that it uses http://rawgit.com/ (commit 91466f8bb85d0514a538a8e53987bb93f73ee98c). The new link is

```
http://rawgit.com/s3rvac/pygal-toggle-graphs/master/pygal-toggle-graphs.js
```

I have tested the script under Chrome 40.0 and other browsers and that link change fixed the problem.

Can you please test it on your system?

**Comment by roperi** [comment]
Thanks for your reply! Although I am sorry I have not replied you before ( I just noticed your reply in my inbox). I'll check later today as soon as I have access to the Windows PC and I'll let you know. Cheers!
