### ISSUE TITLE
Tooltip displaying 'None' for some data points in secondary Y-axis lines

### ISSUE THREAD

**Issue by sctchang** [s3rvac/pygal-toggle-graphs#2]
So I have secondary Y-axis enabled (i.e. pygal.add('SomeLabel', data_point, secondary=True)) and some of the tooltips for certain data points are showing up as 'None' when you hover over them.

This doesn't happen when I add data points with the default Y-axis setting. I am using pygal-toggle-graphs as per your 'Usage' section in the md file. Do you know what is going wrong here?

Thanks for extending pygal with this very sorely needed functionality by the way.

![hoverlabelnone1](https://cloud.githubusercontent.com/assets/606349/6158455/b9ac991a-b207-11e4-973e-89735b64c884.JPG)
![hoverlabelnone2](https://cloud.githubusercontent.com/assets/606349/6158454/b9917aae-b207-11e4-8d93-50ab5a5bf3a9.JPG)

**Comment by s3rvac** [comment]
Thank you for your report. Are you sure that this is caused by my `pygal-toggle-graphs` module? I have tried to reproduce the bug but it does not seem to be related to this modul, i.e. it happens regardless of its presence. If it displays correct values when you stop using this module, please post the source code for the graph so I can reproduce the problem. Otherwise, the [pygal repository](https://github.com/Kozea/pygal) is probably a better place to report this since it seems to be related to `pygal`, not to `pygal-toggle-graphs`.

By the way, do you have any `None`s in your data points? `pygal` seems to show `None` in the graphs when there are `None`s in the data points and `secondary=True` is used.

**Comment by sctchang** [comment]
By Odin's beard, you are very much correct my good sir! I must have noticed the bug AFTER installing `pygal-toggle-graphs`.

Yes, I do have `None`s in my data points, and by default `pygal` is supposed to ignore the `None` data points. While it is doing that correctly when it renders the line, it does seem to screw up the tooltips when `secondary=True` is set.

I'll close this issue and resubmit it in `pygal`'s repository posthaste!
